on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, "386", arm, arm64]
        exclude:
          - goos: windows
            goarch: arm
          - goos: windows
            goarch: arm64
          - goos: darwin
            goarch: "386"
          - goos: darwin
            goarch: arm
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.32
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          build_flags: -trimpath
          md5sum: false
